# Домашнее задание «Библиотека numpy. Вычислительные задачи»


**Задание 1**

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет ```array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])```).

In [1]:
import numpy as np

In [20]:
def create_array_from_n_to_0(n):
    return np.arange(n+1, 1) if n < 0 else np.arange(n)[::-1]
        

In [24]:
print(create_array_from_n_to_0(-10))
print(create_array_from_n_to_0(10))


[-9 -8 -7 -6 -5 -4 -3 -2 -1  0]
[9 8 7 6 5 4 3 2 1 0]


**Задание 2**

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [28]:
def create_matrix_and_find_diag_sum(n):
    matrix = np.diag(create_array_from_n_to_0(n))
    print(matrix)
    print('sum =', matrix.sum())

In [29]:
create_matrix_and_find_diag_sum(5)
create_matrix_and_find_diag_sum(8)

[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]
sum = 10
[[7 0 0 0 0 0 0 0]
 [0 6 0 0 0 0 0 0]
 [0 0 5 0 0 0 0 0]
 [0 0 0 4 0 0 0 0]
 [0 0 0 0 3 0 0 0]
 [0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]]
sum = 28


**Задание 3**

Решите систему уравнений:
```
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3```

In [30]:
from numpy import linalg

In [33]:
a = np.array([
    [4, 2, 1],
    [1, 3, 0], 
    [0, 5, 4]
])

b = np.array([4, 12, -3])

x, y, z = linalg.solve(a, b)
print(f'x = {x}, y = {y}, z = {z}')
print(np.allclose(np.dot(a, linalg.solve(a, b)), b))

x = 0.4666666666666668, y = 3.844444444444444, z = -5.555555555555555
True


**Задание 4**

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:
На сайт заходит очередной посетитель, о покупках которого известно следующее:
```next_user_stats = np.array([0, 1, 2, 0, 0, 0])```

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats



In [38]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [39]:
def cosine(a, b):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """

    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [69]:
max_distance, i = max([(cosine(next_user_stats, user), i) for i, user in enumerate(users_stats, 1)], key=lambda a:a[0]) 
print(f'Пользователь User_ID = {i} наиболее близок к новому. Косинусное расстояние = {max_distance}')

Пользователь User_ID = 8 наиболее близок к новому. Косинусное расстояние = 0.9486832980505138


In [70]:
# в цикле более наглядно. действительно, у 8го пользователя косинусное расстояние наибольшее
for i, user in enumerate(users_stats, 1):
    print(i, cosine(next_user_stats, user))

1 0.19999999999999996
2 0.8451542547285165
3 0.3999999999999999
4 0.7905694150420948
5 0.3999999999999999
6 0.0
7 0.0
8 0.9486832980505138
9 0.0
10 0.0
